title: Aliyas Logs
logo: /assets/images/logo.jpg
email: mail@jainbasilaliyas.in
description: >- 
  ..blog of jainbasil..
baseurl: ""
twitter_username: jainbasil
github_username:  jainbasil
theme: jekyll-theme-so-simple

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

paginate: 10
paginate_path: /page:num/

search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

disqus:
  shortname: aliyas-logs

copyright: "&copy; 2020 - Jain Basil Aliyas"
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square