title: Blog || iiqrah
description: >-
  YouTube &middot; iOS Development &middot; Digital Art
logo: /assets/images/logo.png

baseurl: "/blog"
remote_theme: "mmistakes/so-simple-theme@3.2.0"



read_time: true
words_per_minute: 200


# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

google_fonts:
  - name: "Source Sans Pro"
    weights: "200,200i,400,400i"


twitter:
  username: "i_iqrah"

paginate: 10
paginate_path: /page:num/

search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"


copyright: "&copy; 2020 - iiqrah"
footer_links:
  - title: YouTube
    url: https://www.youtube.com/iiqrah
    icon: fab fa-youtube-square
  - title: Twitter
    url: https://www.twitter.com/i_iqrah
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://www.github.com/iiqrah
    icon: fab fa-github-square
  - title: Dribbble
    url: https://dribbble.com/iiqrah
    icon: fab fa-dribbble-square
  - title: Email
    url: mailto:hello@iiqrah.com
    icon: fa fa-envelope-square
